### PR TITLE
add Ajax response

### PR DESCRIPTION
**Pull request by hoshiseigo**
I added Ajax response to FormAuthenticationScheme.

### CODE REVIEW

**Comment by pedroigor** [comment]
Hey @hoshiseigo, can you give some input on what is the change all about ? Some issue when using PL with JSF/Ajax ?

**Comment by hoshiseigo** [comment]
When you use h:commandButton tag with f:ajax tag, this response is xml. Therefore in this case when session timeout is occured, PL response should be xml.

**Comment by pedroigor** [comment]
In this case, wouldn't be better to just make ```forwardToLoginPage``` protected and then override this method to do that ? This scheme should not have logic specific to a view tech, but be generic.

**Comment by pedroigor** [comment]
This repository is no longer maintained and is archived. For more details, please take a look at http://picketlink.org/keycloak-merge-faq.

**Pull request closed without merging**
