### PR TITLE
Custom authorizers and roles

### PR DESCRIPTION
**Pull request by arthurgregorio**
Fix the problem when the developer wants to use a custom path authorizer and don't want the default ones

### CODE REVIEW

**Comment by pedroigor** [comment]
Hi Arthur.

I'm not sure if we can do that. The reason is that others may want to just add their own custom authorizers in addition to the default ones.

Are you trying to override the behavior for one of the built-in authorizers (role, group, etc) ?

Thanks.

**Comment by arthurgregorio** [comment]
When the default RolePathAuthorizer is called, my model don't match the way that authorizer get the roles for the identity.

For example: my user has groups, groups has roles.

That is, he expected to be the group not the user, as the user has no roles, so he ends up returning false, even if my custom authorizer returns true.

I can override the default behavior of RolePathAutorizer without writing a custom authorizer?

More about the problema here: https://developer.jboss.org/thread/266387

**Comment by pedroigor** [comment]
The way it works, the first negative wins. Which will be always one of the default authorizers.

Considering your use case, the role authorizer should also consider the roles granted to the groups where the user is a member. There is a "inherit privileges" check that should be doing that ...

A possible workaround for your issue is to avoid configuring roles to your paths and define them within your custom authorizer. Would that work for you ?

**Comment by arthurgregorio** [comment]
I need to pass the role, without them i can't check if the path the user wants to access is granted in his roles.

My cutom authorizer is not using the methods from AuthorizationUtil. I create my own AccountManager due to a mix with LDAP and JPA stores that i need to use.

Here is what i do:

```java
    @Override
    public boolean authorize(PathConfiguration pathConfiguration, 
            HttpServletRequest request, HttpServletResponse response) {

        final AuthorizationConfiguration authorizationConfiguration = 
                pathConfiguration.getAuthorizationConfiguration();
        
        final String[] allowedRoles = authorizationConfiguration.getAllowedRoles();

        if (allowedRoles != null) {
            return this.authorizationBean.hasRole(allowedRoles);
        }
        return false;
    }
```
Is the same as default role path authorizer, except for the use of query by user, not by group directly.  

But! 

When you say "There is a "inherit privileges" check that should be doing that ..." i need to enable this? What i need configure to try out this possibility?

**Comment by pedroigor** [comment]
You don't need to configure anything. I've executed a simple test considering User A member of Group B which in turn is granted with Role C [1].

Can you check it out ?

[1] https://github.com/pedroigor/picketlink/commit/6b3100945f8cf6cbc75a70ee539a08403a88e3ab

**Comment by arthurgregorio** [comment]
Basically you set the roles for the group and the user? 

That's what I'm in doubt, because if so, I kind of unnecessary work have a group between the role and the user.

My security model: https://github.com/arthurgregorio/web-budget/tree/master/webBudget/src/main/java/br/com/webbudget/domain/security

And the way i map user to groups them to the roles: https://github.com/arthurgregorio/web-budget/blob/master/webBudget/src/main/java/br/com/webbudget/domain/service/AccountService.java#L69

**Comment by pedroigor** [comment]
No, the role is granted to the group only. The user "inherits" that role as he is a member of that group.

You code looks fine, can't identify why you are not getting the same results as I am.

Can you send me the source for your security model without any dependency to third-party libs such as lombok ? So I can perform some tests here using your model.

**Comment by arthurgregorio** [comment]
My model is the same used by this quickstart from picketlink quickstarts: https://github.com/jboss-developer/jboss-picketlink-quickstarts/tree/master/picketlink-idm-custom-identity-model

The way it works is:

- group has grants to roles
- user has groupmembership with one or more groups

here is the method i use to initialize the model: 

```java
@PostConstruct
protected void initialize() {

    // cria ou recupera do banco a particao
    final Partition partition = this.checkPartition();

    // cria o gestor de identidades
    this.identityManager = this.partitionManager
            .createIdentityManager(partition);

    // checamos se todas as roles estao dentro do sistema
    for (String role : this.authorization.listAuthorizations()) {
        if (!this.hasRole(role)) {
            this.identityManager.add(new Role(role));
        }
    }

    // checamos se existe o grupo default
    if (!this.hasGroup(DEFAULT_ADMIN_GROUP)) {
        this.identityManager.add(new Group(DEFAULT_ADMIN_GROUP));
    }

    // checa se existe o usuario admin
    if (!this.hasUser(DEFAULT_ADMIN_USER)) {

        final User user = new User(DEFAULT_ADMIN_USER);

        user.setName("Administrador");
        user.setCreatedDate(new Date());
        user.setEnabled(true);
        user.setExpirationDate(null);
        user.setEmail("admin@webbudget.com");

        this.identityManager.add(user);

        this.identityManager.updateCredential(
                user, new Password(DEFAULT_ADMIN_PASSWORD));

        // setamos agora as permissoes no grupo
        final Group group = this.getGroup(DEFAULT_ADMIN_GROUP);

        // criamos um gerenciador de relacionamentos
        final RelationshipManager relationshipManager
                = this.partitionManager.createRelationshipManager();

        // adicionamos no grupo, todas as roles do sistema
        for (Role role : this.getRoles()) {
            relationshipManager.add(new Grant(role, group));
        }

        // garantimos ao admin que ele faz parte do grupo administradores
        relationshipManager.add(new GroupMembership(group, user));
    }
}
```
The configuration: 

```java
public void configureInternal(@Observes SecurityConfigurationEvent event) {

    final SecurityConfigurationBuilder builder = event.getBuilder();

    builder.idmConfig()
            .named("jpa.config")
            .stores()
            .jpa()
            .supportType(
                    User.class,
                    Role.class,
                    Group.class,
                    Partition.class)
            .supportGlobalRelationship(  
                    Grant.class,  
                    GroupMembership.class)  
            .supportCredentials(true)
            .mappedEntity(
                    RoleTypeEntity.class,
                    UserTypeEntity.class,
                    GrantTypeEntity.class,
                    GroupTypeEntity.class,
                    PasswordTypeEntity.class,
                    PartitionTypeEntity.class,
                    RelationshipTypeEntity.class,
                    GroupMembershipTypeEntity.class,
                    RelationshipIdentityTypeEntity.class)
            .addContextInitializer(this.contextInitializer)
            .setCredentialHandlerProperty(
                    PasswordCredentialHandler.PASSWORD_ENCODER, 
                    new BCryptPasswordEncoder(10));
}
```
Thanks for the help Pedro! :D

**Comment by pedroigor** [comment]
I've added a new test method to that quickstart [1]. It is working as well. You are using 2.7.0.Final, right ?

[1] https://github.com/jboss-developer/jboss-picketlink-quickstarts/pull/42

**Comment by arthurgregorio** [comment]
Yes, is 2.7.0-FINAL and i made this test too.

```java
public boolean checkForRole(IdentityType account, String authorization) {

    final Role role = this.findRoleByName(authorization);

    // account is a user, role is a role granted to a group and this user 
    // must be in this group to have grant to this role
    return this.relationshipManager.inheritsPrivileges(account, role);
}
```
The return is always true, like the test you made. But when the default Role PathAuthorizer is called and they call `hasRole` from `AuthorizationAl` they fail in check due to not recognize the roles in the user passed as parameter to the quey in this method.

**Comment by arthurgregorio** [comment]
Any news on this?

I wondering if i could by CDI or somewhat tell PL to use my custom account manager like Spring provide to his model the roles for the user (by implementing a interface).

Not least because all the tests I did, it was clear that the problem is in `RolePathAuthorizer`, more specifically the fact that he call the `hasRole` method `AuthorizationUtils` an this method fail with a custom IDM.

**Comment by arthurgregorio** [comment]
Bump!

**Comment by arthurgregorio** [comment]
Someone?

**Pull request closed without merging**
